# Probability

## Introduction to Probabilities
In 1814, Pierre-Simon Laplace wrote:  
> Probability theory is nothing but common sense reduced to calculation. 
... [Probability] is thus simply a fraction whose numerator is the 
number of favorable cases and whose denominator is the number of all 
the cases possible ... when nothing leads us to expect that any one of 
these cases should occur more than any other.

Laplace nailed it. To untangle a probability problem, all you have to do 
is define exactly what the cases are, and careful count the favorable 
and total cases. Let's be clear on our vocabulary words:
- **Trial**
A single occurrence with an outcome that is uncertain until we observe it.  
*For example, rolling a single die.*
- **Outcome**
A possible result of a trial; one particular state of the world. What 
Laplace calls a **case.** *For example:* `4`.
- **Sample Space**
The set of all possible outcomes for the trial.   
*For example,* `{1, 2, 3, 4, 5, 6}`.
- **Event**
A subset of the sample space, a set of outcomes that together have some 
property we are interested in.  
*For example, the event "even die roll" is the set of outcomes* 
`{2, 4, 6}`.
- **Probability**
As Laplace said, the probability of an event with respect to a sample 
space is the "number of favorable cases" (outcomes from the sample space 
that are in the event) divided by the "number of all the cases" in the 
sample space (assuming "nothing leads us to expect that any one of these 
cases should occur more than any other"). Since this is a proper 
fraction, probability will always be a number between 0 (representing an 
impossible event) and 1 (representing a certain event).  
*For example, the probability of an even die roll is 3/6 = 1/2.*

In [155]:
import random #Random Number Generator
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [156]:
#1 Coin Flip Generator | Tails = 0 | Heads = 1
toss = random.randint(0,1)
print(toss)

0


In [157]:
# Coin Flip Generator with a Control Structure (for, if, and while)
toss_results = []
for y  in range (10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[0, 0, 1, 0, 1, 0, 0, 0, 1, 0]


In [158]:
# Coin Flip Generator Controlled that can be reproduced
random.seed(2024)
toss_results = []
for y in range (10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [159]:
# Calculate the probability that you will get heads in 10 coin tosses
toss_results = []
for y in range (1000000):
    result = random.randint(0,1)
    toss_results.append(result)
#print(toss_results)
sum(toss_results)/len(toss_results)

0.499507

In [160]:
from fractions import Fraction


In [161]:
Fraction(1,3) #Representation of a fraction in python

Fraction(1, 3)

In [162]:
# Calculate the Probability to toss an even number in a dice through
even = {2,4,6}
points = {1,2,3,4,5,6} # We assume that the dice are perfectly balanced
set.intersection(even,points)


{2, 4, 6}

In [163]:
def Pr(event,space):
    return Fraction(len(set.intersection(event,space)),len(space))

In [164]:
Pr(even,points)

Fraction(1, 2)

In [165]:
# Calculate the Probability of getting 5 or 6 from rolling a dice
success = {5,6}
points = {1,2,3,4,5,6}
Pr(success,points)

Fraction(1, 3)

This refers to discrete sample space so the probability refers to a discrete event

In [166]:
# box1 = (1,0,0,0) - 1/4
# box2 = (1,1,0,0,0) - 2/5

box1 = np.array([1,0,0,0]) # Vector - ([])
np.random.choice(box1,1) #simulates the list of box 1, the second 1 is one event

array([0])

In [167]:
trial = np.random.choice(box1,1000000)
trial.mean()

np.float64(0.250068)

In [168]:
box2 = np.array([1,0,1,0,0])
trial = np.random.choice(box2,1000000)
trial.mean() #here there are only 2 results 0 and 1 and the result of victory is 1

np.float64(0.400818)

In [169]:
#When there are more than 2 results
success = np.isin(trial,[1])
probability = len(trial[success])/len(trial)
probability

0.400818

In [181]:
yankenpo = np.array([1,2,3])
trial = np.random.choice(yankenpo,10)
success = np.isin(trial,[2]) #.isin returns boolean vectors
probability = len(trial[success])/len(trial)
probability

0.3

In [171]:
yankenpo
trial
success

array([False, False, False, False, False, False,  True,  True, False,
       False])

In [172]:
trial

array([1, 3, 1, 1, 1, 3, 2, 2, 1, 3])

In [182]:
trial[success]

array([2, 2, 2])

In [183]:
results = np.array ([14,22,21,15,18,23,19])
success = np.isin(results,21)
results[success]

array([21])

In [199]:
# The Following problem shows the the conditional probability
# What is the probibility to pull an Ace in a second pull if the first card I already pulled an Ace
# How many Aces are in a deck 4
# How many cards in a deck? 52
# What is the Probability of pulling an Ace on the first pull 4/52 -=> 1/13
# If I already pulled an Ace from a deck how many cards are left? 51 and 3 Aces
# In a second pull what is the probability of pulling an Ace? 3/51 Pr(pull ace in second pull|pull Ace in first pull)
# This probability is is under the condition that the ace is pulled in the first pull
# The formula for this is Pr=3/51
# Pr(A and B)=Pr(A)*Pr(B|A)
# If A and B are independent then the probability of Pr(A|B)=Pr(A)
# Pr(A and B and C)=Pr(A)*Pr(B|A)*Pr(C|A and B) rule of chain?
# Pr(A or B)=Pr(A)+Pr(B)-Pr(A and B)
# In a plane there are 3 bombs, each bomb has 0.4 probability of exploding. So what is the probability of the second bomb exploding?
# What is the probability that the 3 bombs explode at once? 0.4*0.4*.04
# What is the probability that in a waiting room with 10 people, that 2 have the same birthday. and in a waiting room with 20 people, and in a waiting room with 30 people?
def same_birthday(n):
    days = np.arange(1,366)
    bday = np.random.choice(days,n)
    return np.any(np.bincount(bday)>1)

same_birthday(10)
counter = 0
for i in range (10000):
    if same_birthday(10):
        counter += 1

counter/10000

0.1154